[package]
name = "tradier-gui"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.13.1"
eyre = "0.6.5"
once_cell = "1.8.0"
tradier = { path = "../tradier" }
